### PR TITLE
Fix TLS reconnection

### PR DESCRIPTION
**Pull request by pires**
This is a WIP and I'm starting the PR with a TLS reconnect test. Can you please validate @mcqueary?

### CODE REVIEW

**Comment by pires** [comment]
Unfortunately, @ColinSullivan1 @mcqueary this breaks 34 tests.
```
Failed tests:
  ConnectionFactoryTest.testConnectionFactoryProperties:181 nats: no servers available for connection
  ConnectionFactoryTest.testConnectionFactoryStringStringArray:306 nats: no servers available for connection
  ConnectionFactoryTest.testGetHost:564 nats: no servers available for connection
  ConnectionFactoryTest.testGetPort:595 nats: no servers available for connection
  ConnectionFactoryTest.testIsTlsDebug:784 nats: no servers available for connection
  ConnectionFactoryTest.testSetHost:579 nats: no servers available for connection
  ConnectionFactoryTest.testSetServersStringArray:665 nats: no servers available for connection
  ConnectionTest.testBadSid:750 Mock server shouldn't have thrown an exception: null
  ConnectionTest.testCreateConnFailure:638 Should not have connected
  ConnectionTest.testErrOnMaxPayloadLimit:568 expected:<1048576> but was:<10>
  ConnectionTest.testFlushTimeoutFailure:121 Should have thrown a timeout exception
  ConnectionTest.testGetServerInfo:656 expected:<0.[7].2> but was:<0.[9].2>
  ConnectionTest.testResendSubscriptions:1153 expected:<UNSUB 1> but was:<null>
  ConnectionTest.testSendSubscription:268 Should have thrown IOException
  ParserTest.TestParserSplitMsg:477 nats: no servers available for connection
  ParserTest.testLargeArgs:271 nats: no servers available for connection
  ParserTest.testMinusErrDoesNotThrow:166 nats: no servers available for connection
  ParserTest.testParseBadLines:238 nats: no servers available for connection
  ParserTest.testParseGoodLines:135 nats: no servers available for connection
  ProtocolTest.testErrOpAuthorization:333 expected:<nats: [authorization viola]tion> but was:<nats: [no servers available for connec]tion>
  ProtocolTest.testErrOpConnectionEx:316 expected:<nats: [generic error message]> but was:<nats: [no servers available for connection]>
  ProtocolTest.testGetConnectedId:189 nats: no servers available for connection
  ProtocolTest.testMockServerConnection:95 nats: no servers available for connection
  ProtocolTest.testNoInfoSent:361 expected:<nats: [protocol error, INFO not received]> but was:<nats: [no servers available for connection]>
  ProtocolTest.testPingTimer:110 nats: no servers available for connection
  ProtocolTest.testProcessErr:128 nats: no servers available for connection
  ProtocolTest.testProcessErrStaleConnection:173 nats: no servers available for connection
  ProtocolTest.testReadOpNull:347 expected:<nats: [connection read error]> but was:<nats: [no servers available for connection]>
  ProtocolTest.testSendConnectEx:257 expected:<[Mock write I/O error]> but was:<[nats: no servers available for connection]>
  ProtocolTest.testServerParseError:220 nats: no servers available for connection
  ProtocolTest.testServerToClientPingPong:204 nats: no servers available for connection
  ProtocolTest.testTlsMismatchClient:392 expected:<nats: [secure connection not available]> but was:<nats: [no servers available for connection]>
  ProtocolTest.testTlsMismatchServer:376 expected:<nats: [secure connection required]> but was:<nats: [no servers available for connection]>
  ProtocolTest.testVerbose:147 nats: no servers available for connection

Tests run: 213, Failures: 34, Errors: 0, Skipped: 0
```

**Comment by ColinSullivan1** [comment]
@pires The fix itself looks great, and thank you for the contribution!  As seen here, and as we discussed on slack, this is causing issues with the tests.  For a quick fix to immediately address this issue and get tests working, @mcqueary said he'd update the TCPConnection class to include an API to call that will normally create the new TCPConnection, but in mock tests, do what is needed for testing.  Should be a one line update to this PR when it's ready.

**Comment by pires** [comment]
Thanks @ColinSullivan1 for your support, guidance and for letting me shine here 😹 .

**Comment by mcqueary** [comment]
@pires You are very shiny. :)

Following a suggestion you made yesterday, I have created a `TCPConnectionMockFactory` and now inject the factory vs. injecting the `TCPConnectionMock` object directly; this eliminates any need for `ConnectionImpl` to do anything special for mock vs real.

**Comment by pires** [comment]
Awesome @mcqueary, glad I could help somehow. And thanks for taking the time to help me through this. 👏

**Pull request merged**
